general:
  mongodb: mongodb://localhost:27017
  backdate_packets: 10
  remember_planes: 30
  packet_method: dump1090
  status_message_top_planes: 5
  advanced_status: true
  hz: 2
  logs: info  # debug, info, warning, or error

home:
  latitude: 36.6810752
  longitude: -78.8758528

components:  # TODO: components
  easy:
    altitude:
      maximum: 1000000

zones:
  main:  # smaller area randomly picked out for testing
    coordinates:
      [[35.753821, -78.909304],
      [35.755597, -78.904969],
      [35.756642, -78.898232],
      [35.755214, -78.892738],
      [35.753333, -78.888490],
      [35.749293, -78.889606],
      [35.747343, -78.891494],
      [35.746507, -78.895742],
      [35.747482, -78.900806],
      [35.748910, -78.906085],
      [35.751348, -78.910205]]
    levels:
      warn:
        category: really_high_priority
        requirements: easy
        seconds: 60
      alert:
        category: really_high_priority
        requirements: easy
        seconds: 60

  alternate: # Most of raleigh area
    coordinates:
      [[36.279595, -79.349321],
      [35.943933, -79.534100],
      [35.560548, -79.501141],
      [35.058494, -79.138592],
      [35.049501, -78.776043],
      [35.184300, -78.248700],
      [35.435327, -78.017987],
      [35.801494, -77.963055],
      [36.112746, -77.974041],
      [36.254624, -78.226727],
      [36.334318, -78.666180],
      [36.325467, -78.929852],
      [36.343168, -79.259442]]
    levels:
      not_inline_test:
        category: warn
        requirements: easy
        seconds: 60
      inline_test:
        category:
          method: print
          save:
            telemetry_method: all
            calculated_method: all
        requirements: easy
        seconds: 60

categories:
  really_high_priority:
    method: print
    save:
      telemetry_method: all
      calculated_method: all
  warn:
    method: print
    save:
      telemetry_method: all
      calculated_method: all
  alert:
    method: print
    save:
      telemetry_method: all
      calculated_method: all
