services:
  pyaerial:
    image: pyaerial:latest
    container_name: pyaerial
    restart: always
    build:
      context: .
      network: host
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    depends_on:
      - mongodb
    network_mode: host
  mongodb:
    image: mongo:latest
    container_name: pyaerial_database
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /opt/PyAerial/db:/data/db
    network_mode: host
