database:
  uri: mongodb://localhost:27017
  redis_uri: redis://localhost:6379/0

tracking:
  hz: 2
  remember_planes: 30
  backdate_packets: 10
  duplicate_packet_merging: 5
  status_message_top_planes: 5
  advanced_status: true

logging:
  level: info

home:
  latitude: 36.6810752
  longitude: -78.8758528

receivers:
  main:
    type: dump1090
    host: localhost
    port: 30002

zones:
  main:
    coordinates:
      - [35.753821, -78.909304]
      - [35.755597, -78.904969]
      - [35.756642, -78.898232]
      - [35.755214, -78.892738]
      - [35.753333, -78.888490]
      - [35.749293, -78.889606]
      - [35.747343, -78.891494]
      - [35.746507, -78.895742]
      - [35.747482, -78.900806]
      - [35.748910, -78.906085]
      - [35.751348, -78.910205]
    rules:
      - name: warn
        when:
          altitude: { max: 1000 }
          eta: { max: 120 }
        dwell_seconds: 60
        on_activate:
          - method: print
        retain: true
      - name: alert
        when:
          altitude: { max: 500 }
          eta: { max: 60 }
        dwell_seconds: 60
        on_activate:
          - method: print
        retain: true
